### ISSUE TITLE
Upgrades to newer versions of Elgg?

### ISSUE THREAD

**Issue by Danie10** [demyxco/elgg#2]
I got this container up and running quite easily and migrated all my old site data in from a backup. But I noticed this is a v3.x and Elgg is now already at v4.x.  What is the recommended way of upgrading, as I see there does not appear to be any newer versions released of the container for pulling?

**Comment by demyxco** [comment]
Hi. Please check with Elgg's docs on the upgrade process since I'm currently outdated. I will be updating the Docker image when I have time.

**Comment by Danie10** [comment]
OK thanks, so I can run a normal Elgg update from within this container? I thought maybe it was a static, pull-only, container?

**Comment by demyxco** [comment]
The core Elgg files are hosted in the named volume so it's not read only. You'll have to update it manually.

**Comment by Danie10** [comment]
Ah thanks yes I take it under mod and vendor. I'll have a try at that thanks (after creating a backup).

**Comment by demyxco** [comment]
I'll be closing this ticket now. Hope the upgrade went well!
