### ISSUE TITLE
E-mail

### ISSUE THREAD

**Issue by Danie10** [demyxco/elgg#3]
Although I have e-mail addresses set in my profile as well as on site settings, no notification mails seem to be going out. I can't find any Elgg settings for this, so I'm suspecting it must be PHP settings? Is there a way to do this? I don't see anything relevant in the mapped volume for config settings either.

**Comment by demyxco** [comment]
You'll need to use an Elgg plugin that uses a third party SMTP provider since the Elgg Docker image doesn't include any MTAs.

**Comment by Danie10** [comment]
Great thank you I'll look at those plugins.

**Comment by Danie10** [comment]
Actually see now that there were e-mail settings in the settings.php file, and after configuring there, SMTP mail is working 100%.

**Comment by demyxco** [comment]
Glad you got it working! I haven't touched Elgg in a while and I'm happy that they've finally added that in the settings page.
